source: "app"
destination: "dist"
prose:
  rooturl: 'app'
  ignore:
    - 'robots.txt'
    - 'favicon.ico'
    - '_includes'
    - '_layouts'
    - 'scripts'
    - 'js'
    - 'styles'
    - 'sass'
    - 'fonts'
    - '_data'
    - 'images/colorbox'
    - 'config.rb'
    - '_posts/products'
    - '_posts/ranges'
    - 'media'

