version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.2.7-node
    working_directory: ~/repo
    environment:
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install --assume-yes openjdk-7-jre
      - run: sudo apt-get install python-pip
      - run: sudo pip install csvkit --allow-external csvkit --allow-unverified csvkit
      - run: sudo apt-get install libfftw3-double3 imagemagick
      - checkout
      - run: bundle install
      - run: npm install
      - run: npm run generate
      - run: npm run build
      - deploy:
          name: deploy to AWS
          command: s3_website push
